name: Update Contributors in README
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: An action workflow to automate contributors in README
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
