name: PR Description Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Description
        id: check_description
        run: |
          description="${{ github.event.pull_request.body }}"

          # Check if the description is empty
          if [ -z "$description" ]; then
            echo "::error::Description is missing!"
            exit 1
          fi

          # Check for issue number or 'Fix #NEW'
          if [[ ! "$description" =~ [Ff]ix\ #[0-9]+ && ! "$description" =~ [Ff]ix\ #NEW ]]; then
            echo "::error::PR description must contain an issue number or 'Fix #NEW'"
            exit 1
          fi
